<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33005639"><DocLocation><![CDATA[C:\framework\QTP-Hybrid-Framework\QTP-Hybrid-Framework\TestCases\Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Login]]></DName>
<Res><![CDATA[Res22]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Silverlight, WinForms.]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:01]]></Time>
<TimeTick>1676284981</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Step rID="T5">
<Obj ><![CDATA[Replay Start]]></Obj>
<Details ><![CDATA[This run was performed on Internet Explorer without the required 'Enable third-party browser extension' option selected. Therefore, steps performed on this browser may have unexpected results.  It is recommended to select the 'Tools > Internet Options > Advanced > Enable third-party browser extensions' option in Internet Explorer and then run this test again.]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:01]]></Time>
<TimeTick>1676284981</TimeTick>
<NodeArgs eType="User" icon="4" nRep="8" status="Failed" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[Replay Start]]></Disp>
</NodeArgs>
</Step>
<Action rID="T6">
<AName><![CDATA[login]]></AName>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:23]]></Time>
<TimeTick>1676285003</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:23]]></Time>
<TimeTick>1676285003</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:28]]></Time>
<TimeTick>1676285008</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:28]]></Time>
<TimeTick>1676285008</TimeTick>
<NodeArgs eType="User" icon="4" nRep="30" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:29]]></Time>
<TimeTick>1676285009</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="32" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:29]]></Time>
<TimeTick>1676285009</TimeTick>
<NodeArgs eType="User" icon="4" nRep="33" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman2@Rahman.com"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="User" icon="4" nRep="37" status="Passed" >
<Disp><![CDATA[Value - 'Rahman2@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="User" icon="4" nRep="40" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="User" icon="4" nRep="44" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="User" icon="4" nRep="47" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:30]]></Time>
<TimeTick>1676285010</TimeTick>
<NodeArgs eType="User" icon="4" nRep="51" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:32]]></Time>
<TimeTick>1676285012</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:32]]></Time>
<TimeTick>1676285012</TimeTick>
<NodeArgs eType="User" icon="4" nRep="55" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:34]]></Time>
<TimeTick>1676285014</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="58" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:34]]></Time>
<TimeTick>1676285014</TimeTick>
<NodeArgs eType="User" icon="4" nRep="59" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="User" icon="4" nRep="62" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@Nandini.com"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="65" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="User" icon="4" nRep="66" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@Nandini.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="68" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="User" icon="4" nRep="69" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nandini@12345"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="72" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:35]]></Time>
<TimeTick>1676285015</TimeTick>
<NodeArgs eType="User" icon="4" nRep="73" status="Passed" >
<Disp><![CDATA[Value - 'Nandini@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:36]]></Time>
<TimeTick>1676285016</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="75" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:36]]></Time>
<TimeTick>1676285016</TimeTick>
<NodeArgs eType="User" icon="4" nRep="76" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:36]]></Time>
<TimeTick>1676285016</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="79" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:36]]></Time>
<TimeTick>1676285016</TimeTick>
<NodeArgs eType="User" icon="4" nRep="80" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:37]]></Time>
<TimeTick>1676285017</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="83" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:37]]></Time>
<TimeTick>1676285017</TimeTick>
<NodeArgs eType="User" icon="4" nRep="84" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:39]]></Time>
<TimeTick>1676285019</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="87" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:39]]></Time>
<TimeTick>1676285019</TimeTick>
<NodeArgs eType="User" icon="4" nRep="88" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="User" icon="4" nRep="91" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Lavish@Lavish.com"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Value - 'Lavish@Lavish.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="User" icon="4" nRep="95" status="Passed" >
<Disp><![CDATA[Value - 'Lavish@Lavish.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="97" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="User" icon="4" nRep="98" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Lavish@12345"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="101" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Value - 'Lavish@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="User" icon="4" nRep="102" status="Passed" >
<Disp><![CDATA[Value - 'Lavish@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="104" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="User" icon="4" nRep="105" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="108" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:40]]></Time>
<TimeTick>1676285020</TimeTick>
<NodeArgs eType="User" icon="4" nRep="109" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Log out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:43]]></Time>
<TimeTick>1676285023</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="112" >
<Disp><![CDATA[[ Log out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA['[ Log out ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:43]]></Time>
<TimeTick>1676285023</TimeTick>
<NodeArgs eType="User" icon="4" nRep="113" status="Passed" >
<Disp><![CDATA['[ Log out ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Demo Web Shop ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:45]]></Time>
<TimeTick>1676285025</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="115" >
<Disp><![CDATA[[ Demo Web Shop ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA['[ Browser ] browser' closed]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-02-2023 - 16:13:45]]></Time>
<TimeTick>1676285025</TimeTick>
<NodeArgs eType="User" icon="4" nRep="116" status="Passed" >
<Disp><![CDATA['[ Browser ] browser' closed]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-02-2023 - 16:13:23" eTime="13-02-2023 - 16:13:45" passed="26" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="9" status="Passed" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[Login Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-02-2023 - 16:13:00" eTime="13-02-2023 - 16:13:45" passed="26" failed="1" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Login Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>