<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33005639"><DocLocation><![CDATA[C:\framework\QTP-Hybrid-Framework\QTP-Hybrid-Framework\TestCases\OrangeHybridFramework]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[OrangeHybridFramework]]></DName>
<Res><![CDATA[Res7]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:57]]></Time>
<TimeTick>1676357877</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:57]]></Time>
<TimeTick>1676357877</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:58]]></Time>
<TimeTick>1676357878</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[login]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:58]]></Time>
<TimeTick>1676357878</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:58]]></Time>
<TimeTick>1676357878</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:58]]></Time>
<TimeTick>1676357878</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" Source="login" SourceLine="1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63eb2bfa0109e1834d5ea387629418780ee4ae197a55"]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:59]]></Time>
<TimeTick>1676357879</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" Source="login" SourceLine="2" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:27:59]]></Time>
<TimeTick>1676357879</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="login" SourceLine="3" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="17" Source="login" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="16" Source="login" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 12:27:58" eTime="14-02-2023 - 12:27:59" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[pim]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:02]]></Time>
<TimeTick>1676357882</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:02]]></Time>
<TimeTick>1676357882</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:02]]></Time>
<TimeTick>1676357882</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="32" Source="pim" SourceLine="1" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" Source="pim" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:05]]></Time>
<TimeTick>1676357885</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Type for hints....Set]]></Obj>
<Details plainTxt="False" ><![CDATA["David"]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:05]]></Time>
<TimeTick>1676357885</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="pim" SourceLine="2" >
<Disp><![CDATA[Type for hints....Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:05]]></Time>
<TimeTick>1676357885</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" Source="pim" SourceLine="3" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:05]]></Time>
<TimeTick>1676357885</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" Source="pim" SourceLine="4" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" Source="pim" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:06]]></Time>
<TimeTick>1676357886</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Gopavaram"]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:06]]></Time>
<TimeTick>1676357886</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="48" Source="pim" SourceLine="5" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rajyalakshmi"]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:06]]></Time>
<TimeTick>1676357886</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" Source="pim" SourceLine="6" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:06]]></Time>
<TimeTick>1676357886</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" Source="pim" SourceLine="7" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="47" Source="pim" SourceLine="5" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_6]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:07]]></Time>
<TimeTick>1676357887</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:07]]></Time>
<TimeTick>1676357887</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" Source="pim" SourceLine="8" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Save_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:07]]></Time>
<TimeTick>1676357887</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" Source="pim" SourceLine="9" >
<Disp><![CDATA[Save_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Employee List.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:07]]></Time>
<TimeTick>1676357887</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" Source="pim" SourceLine="10" >
<Disp><![CDATA[Employee List.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="57" Source="pim" SourceLine="8" >
<Disp><![CDATA[OrangeHRM_6]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:08]]></Time>
<TimeTick>1676357888</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Type for hints....Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Gopavaram"]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:08]]></Time>
<TimeTick>1676357888</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="69" Source="pim" SourceLine="11" >
<Disp><![CDATA[Type for hints....Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:08]]></Time>
<TimeTick>1676357888</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="72" Source="pim" SourceLine="14" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[WebCheckBox]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"WebCheckBox"&nbsp;(of&nbsp;class&nbsp;WebCheckBox).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:29]]></Time>
<TimeTick>1676357909</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[WebCheckBox]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>role = <br>Mercury Class = WebCheckBox<br>Index = 1<br>Html Tag = INPUT<br>acc_name = <br>_xpath = //DIV[@role="cell"][1]/DIV[1]/DIV[1]/LABEL[1]/INPUT[1]<br>|Visible = -1<br>Value = 0<br>Type = checkbox<br>Name = <br>Html Id = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:29]]></Time>
<TimeTick>1676357909</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="118" status="Warning" nType="Description" Source="pim" SourceLine="15" >
<Disp><![CDATA[WebCheckBox]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="117" status="Failed" nType="Run Error" Source="pim" SourceLine="15" >
<Disp><![CDATA[WebCheckBox]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="68" status="Failed" Source="pim" SourceLine="11" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="30" status="Failed" Source="pim" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:29]]></Time>
<TimeTick>1676357909</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;WebCheckBox&quot; (of class WebCheckBox).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (16): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM_2&quot;).WebCheckBox(&quot;WebCheckBox&quot;).Set &quot;ON&quot;&quot;. ]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:29]]></Time>
<TimeTick>1676357909</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="120" status="Failed" Source="pim" SourceLine="15" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14-02-2023 - 12:28:33]]></Time>
<TimeTick>1676357913</TimeTick>
<NodeArgs eType="General" icon="12" nRep="121" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="119" status="Failed" Source="pim" SourceLine="15" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 12:27:59" eTime="14-02-2023 - 12:28:33" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="26" status="Failed" >
<Disp><![CDATA[pim Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[OrangeHybridFramework Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 12:27:56" eTime="14-02-2023 - 12:28:33" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test OrangeHybridFramework Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>