<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33005639"><DocLocation><![CDATA[C:\framework\QTP-Hybrid-Framework\QTP-Hybrid-Framework\TestCases\copyAction]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[copyAction]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[login]]></AName>
<Action rID="T5">
<AName><![CDATA[Copy of login]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:19]]></Time>
<TimeTick>1676445619</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:19]]></Time>
<TimeTick>1676445619</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="Copy of login" SourceLine="0" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Copy of login" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:41]]></Time>
<TimeTick>1676445641</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (5 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (5 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Welcome: Mercury Tours<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demo.guru99.com/test/newtours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Welcome: Mercury Tours<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=7<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:41]]></Time>
<TimeTick>1676445641</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Copy of login" SourceLine="1" >
<Disp><![CDATA["Welcome: Mercury Tours"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:41]]></Time>
<TimeTick>1676445641</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[REGISTER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:41]]></Time>
<TimeTick>1676445641</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" Source="Copy of login" SourceLine="1" >
<Disp><![CDATA[REGISTER.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" Source="Copy of login" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:45]]></Time>
<TimeTick>1676445645</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Gopavaram"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:45]]></Time>
<TimeTick>1676445645</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="22" Source="Copy of login" SourceLine="2" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rajyalakshmi"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:45]]></Time>
<TimeTick>1676445645</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Copy of login" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[phone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["8332867150"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:45]]></Time>
<TimeTick>1676445645</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="Copy of login" SourceLine="4" >
<Disp><![CDATA[phone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["r161176@rguktrkv.ac.in"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:46]]></Time>
<TimeTick>1676445646</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" Source="Copy of login" SourceLine="5" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Ashramam Nagar"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:46]]></Time>
<TimeTick>1676445646</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" Source="Copy of login" SourceLine="6" >
<Disp><![CDATA[address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Badvel"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:46]]></Time>
<TimeTick>1676445646</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" Source="Copy of login" SourceLine="7" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[state.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Andhra Pradesh"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:46]]></Time>
<TimeTick>1676445646</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" Source="Copy of login" SourceLine="8" >
<Disp><![CDATA[state.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[postalCode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["516227"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:46]]></Time>
<TimeTick>1676445646</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="43" Source="Copy of login" SourceLine="9" >
<Disp><![CDATA[postalCode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[country.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["INDIA"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:47]]></Time>
<TimeTick>1676445647</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="46" Source="Copy of login" SourceLine="10" >
<Disp><![CDATA[country.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Gopavaram Rajyalakshmi"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:47]]></Time>
<TimeTick>1676445647</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" Source="Copy of login" SourceLine="11" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4cd845d64ab7aff332c9e8e9e89626135ffaa9b5f67dd2813"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:47]]></Time>
<TimeTick>1676445647</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="Copy of login" SourceLine="12" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[confirmPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e4cd8be09d2b51139b2123ac0feed1058210fa811471947a6d"]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:47]]></Time>
<TimeTick>1676445647</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="55" Source="Copy of login" SourceLine="13" >
<Disp><![CDATA[confirmPassword.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Submit Query.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:47]]></Time>
<TimeTick>1676445647</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="58" Source="Copy of login" SourceLine="14" >
<Disp><![CDATA[Submit Query.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="21" Source="Copy of login" SourceLine="2" >
<Disp><![CDATA[Register: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Register: Mercury Tours_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:52]]></Time>
<TimeTick>1676445652</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[SIGN-OFF.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 12:50:52]]></Time>
<TimeTick>1676445652</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="62" Source="Copy of login" SourceLine="15" >
<Disp><![CDATA[SIGN-OFF.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="61" Source="Copy of login" SourceLine="15" >
<Disp><![CDATA[Register: Mercury Tours_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Copy of login" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 12:50:19" eTime="15-02-2023 - 12:50:52" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[Copy of login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T28">
<AName><![CDATA[Action1 [rediff_2]]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Rediffmail Free Unlimited]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:13]]></Time>
<TimeTick>1676445673</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA["Rediffmail Free Unlimited"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (5 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (5 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Rediffmail Free Unlimited Storage<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Rediffmail Free Unlimited Storage<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=http://register.rediff.com/register/register.php?FormName=user_details<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Rediffmail Free Unlimited Storage<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=12<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:13]]></Time>
<TimeTick>1676445673</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" Source="Action1 [rediff_2]" SourceLine="0" >
<Disp><![CDATA["Rediffmail Free Unlimited"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Rediffmail Free Unlimited]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:13]]></Time>
<TimeTick>1676445673</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[name522d3586.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Gopavaram Rajyalakshmi"]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:13]]></Time>
<TimeTick>1676445673</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" Source="Action1 [rediff_2]" SourceLine="0" >
<Disp><![CDATA[name522d3586.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[login522d3586.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["rajyalakshmi_gopavaram"]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:13]]></Time>
<TimeTick>1676445673</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" Source="Action1 [rediff_2]" SourceLine="1" >
<Disp><![CDATA[login522d3586.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Check availability.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:14]]></Time>
<TimeTick>1676445674</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="76" Source="Action1 [rediff_2]" SourceLine="2" >
<Disp><![CDATA[Check availability.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[passwd522d3586.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e0fcb7da0714ab841fd41d03b7"]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:14]]></Time>
<TimeTick>1676445674</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="79" Source="Action1 [rediff_2]" SourceLine="3" >
<Disp><![CDATA[passwd522d3586.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[confirm_passwd522d3586.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e0fcba1112f2f8ed9b1083c6b3"]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:14]]></Time>
<TimeTick>1676445674</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" Source="Action1 [rediff_2]" SourceLine="4" >
<Disp><![CDATA[confirm_passwd522d3586.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[altemail522d3586]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"altemail522d3586"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:34]]></Time>
<TimeTick>1676445694</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[altemail522d3586]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV[@id="div_altemail"]/TABLE[1]/TBODY[1]/TR[1]/TD[3]/INPUT[1]<br>|rows = 0<br>placeholder = <br>Name = altemail522d3586<br>Max Length = 100<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:34]]></Time>
<TimeTick>1676445694</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="126" status="Warning" nType="Description" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[altemail522d3586]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="125" status="Failed" nType="Run Error" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[altemail522d3586]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="69" status="Failed" Source="Action1 [rediff_2]" SourceLine="0" >
<Disp><![CDATA[Rediffmail Free Unlimited]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="66" status="Failed" Source="Action1 [rediff_2]" SourceLine="0" >
<Disp><![CDATA[Rediffmail Free Unlimited]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Rediffmail Free Unlimited]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:35]]></Time>
<TimeTick>1676445695</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;altemail522d3586&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (6): &quot;Browser(&quot;Rediffmail Free Unlimited&quot;).Page(&quot;Rediffmail Free Unlimited&quot;).WebEdit(&quot;altemail522d3586&quot;).Set &quot;rajyalakshmigopavaram@gmail.com&quot;&quot;. ]]></Details>
<Time><![CDATA[15-02-2023 - 12:51:35]]></Time>
<TimeTick>1676445695</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="128" status="Failed" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Rediffmail Free Unlimited]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[15-02-2023 - 12:52:08]]></Time>
<TimeTick>1676445728</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[altemail522d3586]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"altemail522d3586"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[15-02-2023 - 12:52:08]]></Time>
<TimeTick>1676445728</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[altemail522d3586]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV[@id="div_altemail"]/TABLE[1]/TBODY[1]/TR[1]/TD[3]/INPUT[1]<br>|rows = 0<br>placeholder = <br>Name = altemail522d3586<br>Max Length = 100<br>Html Id = <br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[15-02-2023 - 12:52:08]]></Time>
<TimeTick>1676445728</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="173" status="Warning" nType="Description" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[altemail522d3586]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="172" status="Failed" nType="Run Error" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[altemail522d3586]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="171" status="Failed" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[Rediffmail Free Unlimited]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="127" status="Failed" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[Rediffmail Free Unlimited]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Rediffmail Free Unlimited]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[15-02-2023 - 12:52:08]]></Time>
<TimeTick>1676445728</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;altemail522d3586&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (6): &quot;Browser(&quot;Rediffmail Free Unlimited&quot;).Page(&quot;Rediffmail Free Unlimited&quot;).WebEdit(&quot;altemail522d3586&quot;).Set &quot;rajyalakshmigopavaram@gmail.com&quot;&quot;. ]]></Details>
<Time><![CDATA[15-02-2023 - 12:52:08]]></Time>
<TimeTick>1676445728</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="175" status="Failed" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[15-02-2023 - 12:52:19]]></Time>
<TimeTick>1676445739</TimeTick>
<NodeArgs eType="General" icon="15" nRep="176" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="174" status="Failed" Source="Action1 [rediff_2]" SourceLine="5" >
<Disp><![CDATA[Rediffmail Free Unlimited]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15-02-2023 - 12:50:52" eTime="15-02-2023 - 12:52:19" passed="0" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="13" nRep="64" status="Failed" >
<Disp><![CDATA[Action1 [rediff_2] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="15-02-2023 - 12:50:19" eTime="15-02-2023 - 12:52:20" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[copyAction Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="15-02-2023 - 12:50:15" eTime="15-02-2023 - 12:52:20" passed="1" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test copyAction Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>